apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: library-pub-sub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    # value: "amqp://guest:guest@localhost:5672"
    value: "amqp://guest:guest@rabbitmq:5672"
  - name: durable
    value: false
  - name: deletedWhenUnused
    value: false
  - name: autoAck
    value: false
  - name: reconnectWait
    value: 0
  - name: concurrency
    value: parallel
  - name: contentType
    value: "text/plain"
  